### ISSUE TITLE
Errors not being logged

### ISSUE THREAD

**Issue by oragorn** [RehanSaeed/ASP.NET-MVC-Boilerplate#8] opened 2015-04-13 09:31 UTC
I noticed that the project is not logging 404 and 500 among other errors. Is this intentional? How do I configure the project to log these errors on Elmah?

My problem runs deeper than this. My WebApi setup is throwing a 500, but I can't find the reason because the response is showing the custom error page.

**Comment by RehanSaeed** [comment] 2015-04-13 11:45
Thanks for logging this issue. Take a look at the change log or create a new project from the template (I've not yet checked in the code but will this afternoon).

I've not fixed the issue with logging 500 errors. When I introduced an 'Error' folder yesterday to contain the new static error pages for 503 and 504 errors, this conflicted with the '/error' route. I've now renamed the '/error' route to 'error/internalservererror'.

I'm not sure why Elmah is not logging 404 errors. I've raised <a href="https://github.com/alexbeletsky/elmah-mvc/issues/60">this</a> issue with Elmah.MVC. I'll try to play around with it more and see if I can figure it out.

**Comment by RehanSaeed** [comment] 2015-04-15 16:18
I have found that the problem is with Elmah.MVC. It stops logging correctly if we use only attribute routing. You can fix the issue if you add the code below. I am waiting for a response from Elmah.MVC before I add this code as I want to understand what is going wrong.

```
routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
```

**Comment by RehanSaeed** [comment] 2015-05-12 08:36
The default route above has been added by default, with a comment about it being required to satisfy Elmah.

**Closed** 2015-05-12 08:36 UTC
